# frozen_string_literal: true

source 'https://rubygems.org'

gem 'http'
gem 'jwt', '~> 2.2', '>= 2.2.1'
gem 'sinatra'
gem 'sinatra-contrib'

group :development, :test do
  gem 'rack-test'
  gem 'rspec'
end
